apiVersion: v1
kind: Service
metadata:
  name: simon-service
  namespace: logging
spec:
  type: NodePort
  selector:
    app: simon
  ports:
    - protocol: "TCP"
      port: 3001
      targetPort: 3001
      nodePort: 32023
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon
  namespace: logging
  labels:
    app: simon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simon
  template:
    metadata:
      labels:
        app: simon
    spec:
      containers:
      - name: log-simon
        image: davter23/flask-test
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
